name = "disc-commands"
workers_dev = true
compatibility_date = "2021-07-22"
main = "./index.js"

# Account ID of your Cloudflare account
account_id = "64bebdd8439aa2828fd93170fd7e2e88"

# The public key of your Discord application
[vars]
APPLICATION_PUBLIC_KEY = "f73ae9e497f66012e098b5b1a912ac6fd172d1f00bb2d24c1531edfca81973cb"
